version: "3"

services:
  web:
    container_name: web
    build: ./app
    ports:
      - "5000:5000"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app
  
  celery_worker:
    container_name: celery_worker
    build: ./app
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./app:/app
  
  redis:
    container_name: redis
    image: redis
    ports: 
      - "6379:6379"